---
title: "Workflow of 'n_from_power()'"
author: "Shu Fai Cheung & Sing-Hang Cheung"
output:
  html_document:
    fig.align: "center"
    toc: true
    number_sections: false
bibliography: references.bib
csl: apa.csl
---

(**DRAFT: WORK-IN-PROGRESS**)

```{r echo = FALSE}
library(DiagrammeR)
```

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Goal

This technical appendix describes the
workflow of `n_from_power()` in
[power4mome](https://sfcheung.github.io/power4mome/).

# `n_from_power()`

The workflow of `n_from_power()`.

```{r fig-n_from_power, fig.cap = "From Power to Sample Size", echo = FALSE}
# https://mermaid.live/edit#pako:eNqtV3tvGjkQ_yrWVpVAIhGPUhKqXrXLQgIJUZWkfxxHtXJ2DWxv8XJebxIa5bvf2GPvgybXSlekKJ7xb94Pw5MTphFzhs4qSR_CDRWS3PpLTsjbtyRMaJb5bEUitqJ5IskqTpLhmzF8JpMPhyAmRCo4KDOwycSHzw-wTIINxiOD8n2FA5TCLdzGX0tnEsOt3DByQ7e7BP7F3xlp8ObS-dpUKNdtVEAxj2VME8Izso7vGa8xBcvA72zpoKAHgiOaJGSXPjDxTrJMBnf7gJNVKrQcL6AjgM6ZWDPNN3rI0dEfRAkEHYvztS-SUNRJwlzcMwKwVSyD2KAgftdXXn_ZRVQyfdep3nnlXV39GC5umNROZOyfnPGQkXRFuGC7rEWu4Y9CIiD4HRiXAoKu6J28In2dVUBnr4DeaDuHipWUp0K5UXWEsA-uvKcnyPGUhCmXksYgD7g1qNfpWTrPzxZYyQeWTDJxDzUDq5jKhN2zBORTcIuKcFMaGdkG4Ppair2uDA--mbg8VRY3-pZnUqeK3NGMRSTlddUYoBYFUCk9_nmflK1QSE1-rWW8s5dbxvRMpwzzXOVyWs8g5CmLI2OC8rUuFfgXbyGRUS28T5Vsn9dmhpOHWG6s-STNQIFOJNzVy9U00pVi8SDNZQsBeNTJ06cwxv-qJ3XQQFXiUW0-Nr6CE3d7bbGShcKg7o7_KEGcEV6Cvf_pnVbyixMPSL_euT-p4lRV0eV7MoJSxjxMclO-aqartZq6ZiLB302sC3N7_WVs7U-9eikbtInlhKl7Tb0OuXHXJNkWcsoyclOqG_2O0k4XP_g8cS-NFY2YqTTgbTXYmav41gz5-BHSx2kSKE4dp4HzVKjoKIdZZjjaCVsdaNTdesUecfZhS9olGcAuCw4W1kx5PqeP8Tbf4s7TgAw6gIYbFn0qoRfKgwbG0MSUvux4s-rPhS0nDzSihekzZ8y1IUC1OWm95myYFT88u7JTcuUOf5_iy9p8Bo8vTChp6PZulkJzEPoMWqnAvoNs7IrW0K_6Qr3q10zmgtcQX5v22ddz47r4uiPh4YuNxAjfZCR8fHiRGKMKd6xJz0Uyy-_Wgu425FbVklym6c4-XYjz8A0CgvzJMsMzd6Py7iqtstC-5-MLg8QYHwwkJvgOIHGGyx6Jc1wdNXvnrlmulnRLkDV87pmdY0nX7kfLsIACMbL7zDL8Yv0an6d2qRckznDNu6lrlpEhPbN8DDkyywPJWVWF9X26MKuhjplVMbNFlVsYn7lmlGtY13LdA3D9oqrb7IM6Y1FFvSiq2wi-pBY7ombwouJclWnHs853S6ZVf-EVuwEZl2auCwrHEcm5HTRNLhZOy9kysaVxBF_bn9TV0oGx2sLrOYRjRMXfS2fJnwFHc5ne7HnoDKXIWcsRab7eOMMV7Degcr31_ZjCrGwL7o7yRZpurQiLYpmKOf5I0L8VNMQZPjmPzvCkc9zuvu-fdk56ndP2oN9y9s7wqNvut4977X53MOh2Bifves8t57vW2T_u9vrt03a33x_0BgBpOWuhAjH-Qc6ZGKU5l86w877Xbj__C8fD2-Y
mermaid('
flowchart TD
  %% classDef default fill:#EEEEFF;
  %% classDef errornode fill:#FFDDDD;
  %% classDef startend fill:#DDFFDD;

  ZA(["Find the Sample Size (n)"])
  AA("Find the initial ns given the initial results")
  AB("Call power4test_by_n for the ns")
  AC("Merge the results --> by_n_1")
  AD("Fit a power curve -> fit_i")
  %% ADA("Update fit_1")
  %% ADB("Update by_n_1")
  AE("Set the sequence of nreps, Rs, and ns per trial")
  %% AF("Set the sequence of Rs")
  %% AG("Set the sequence of # of ns per trial")

  BA("Start a trial")

  BB{{"CI conttains target power"}}

  BBA("Update the interval of power levels to search")

  BC("Find ns to try --> n_j")
  BD("Adjust nrep based on power levels of ns --> nrep_j")
  BE("Call power4test_by_n for the ns --> by_n_j")
  BF("Merge the results --> by_n_1")
  BG("Fit a power curve --> fit_1")

  BH{{"Is target power inside the range of estimated power levels?"}}

  BHA("Find the n with power closest to the target power")
  BHAA("Update n_out, power_out, nrep_out, ci_out, and by_n_out")

  BHB("Estimate n by the power curve")
  BHBA("Call power4test_by_n for this n")
  BHBB("Update n_out, power_out, nrep_out, ci_out, and by_n_out")
  BHBC("Merge the results --> by_n_1")
  BHBD("Update the power curve --> fit_1")

  BI{{"Any CIs include the target power?"}}

  BIA("Set ci_hit to TRUE")
  BIB("Find the n (a) with CI include the target power and (b) smalles SE")
  BIC("Update n_out, power_out, nrep_out, ci_out, and by_n_out")

  BIZ("Set ci_hit to FALSE")

  BJ{{"ci_hit?"}}

  BJA{{"nrep_out == final_nrep?"}}

  BJAA{{"More than one nrep left?"}}

  BJAAA("Next nrep, R, and ns_per_trial")

  BJZ("Maximum # of trials reached?")

  BK{{"(ci_hit) and (nrep_out == final_nrep)?"}}

  BKA("Set n_final, by_n_final, power_final, ci_final, nrep_final, i_final")

  BKB("Set to NA: n_final, by_n_final, power_final, ci_final, nrep_final, i_final")

  BL("Estimate n_x by the power curve (fit_1)")

  BM("Prepare the output")


  ZZ(["Return the output"])

  ZA --> AA
  AA --> AB
  AB --> AC
  AC --> AD
  AD --> AE

  AE --> BA

  subgraph Trial Loop

  BA --> BB
  BB -- Yes --> BBA --> BC
  BB -- No --> BC
  BC --> BD
  BD --> BE
  BE --> BF
  BF --> BG
  BG --> BH
  BH -- Yes --> BHA
  BHA --> BHAA
  BH -- No --> BHB
  BHB --> BHBA
  BHBA --> BHBB
  BHBB --> BHBC
  BHBC --> BHBD

  BHBD --> BI
  BHAA --> BI

  BI -- Yes --> BIA
  BIA --> BIB
  BIB --> BIC
  BIC --> BJ

  BI -- No --> BIZ
  BIZ --> BJ

  BJ -- No --> BJZ

  BJ -- Yes --> BJA
  BJA -- No --> BJAA
  BJAA -- Yes --> BJAAA
  BJAA -- No --> BJZ
  BJAAA --> BJZ
  BJZ -- No --> BA
  BJAA -- No --> BA

end

  BJZ -- Yes --> BK
  BJA -- Yes --> BK


  BK -- Yes --> BKA
  BK -- No --> BKB

  BKA --> BL
  BKB --> BL

  BL --> BM

  BM --> ZZ
', height = 4500, width = 700)
```
